# Generated by Django 5.0.6 on 2024-08-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
