# Generated by Django 5.0.6 on 2025-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin1', models.CharField(max_length=100)),
                ('admin2', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('predicted_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
