# Generated by Django 5.0.6 on 2024-08-27 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0010_remove_order_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sold_orders', to='market_place.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processed', max_length=10),
        ),
    ]
