# Generated by Django 5.0.6 on 2024-08-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0011_order_seller_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
